# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webgroup',
            options={'verbose_name': '群友关系', 'verbose_name_plural': '群友关系'},
        ),
        migrations.AddField(
            model_name='webgroup',
            name='head_img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
